JdeRobot/base

README.md
To get JdeRobot built, there are many dependencies, which are not totally covered in the `README.md` file(Like the `GTK` stuff). 
Add a link to the `Installation Manual` to make things clear.
=> The user should follow the installation manual when missing dependencies

src/stable/components/rgbdManualCalibrator/drawarea.cpp, src/stable/components/rgbdViewer/drawarea.cpp
Details here: https://github.com/RoboticsURJC/JdeRobot/issues/17
There is an extra "%s" in format string. There is two solutions depending on what was that workarround originally.
=> Fix #17: Warning about sscanf string format in two files drawarea.cpp

README.md
As per the information at website of Ogre3d, Ubuntu 14.04 and above need to use ` libogre-1.9-dev` as the package name for installation. 
http://www.ogre3d.org/tikiwiki/Installing+the+Ogre+SDK?tikiversion=Linux
Opening this pull request from Master branch itself since the change is small and unbreaking, Ubuntu being the most used distro.
#GSoC15
=> Appends readme with newer package name of libogre-dev for Ubuntu 14.04

Deps/gazebo/CMakeLists.txt
Hi!
Everytime I'm compiling I have to change this line. It will be still compatible for people with the 5.0.0 installed.
=> Update Deps/gazebo CMakeLists

src/stable/components/gazeboserver/plugins/quadrotor/interfaces/navdatai.cpp
Hi JdeRobot,
I've made a little change on the quadrotor's drivers. The navdata structure returned with the getNavData method on the navdatai.cpp file now contains 10 instead of 0. This change is usefull to distinguish the simulated ArDrone from the real one.
Best regards,
Daniel
=> QuadrotorPlugin: Version 5 navdata field vehicle returns 10.

src/stable/components/kinect2server/README.md
Some dependencies need to be installed before running `./install_ubuntu.sh` and the `libturbojpeg` linker issue need to be fixed when necessary.
=> Add more references when building libfreenect2

src/stable/components/gazeboserver/plugins/quadrotor/CMakeLists.txt
The CMakeLists.txt file now includes colorspacesmm on the quadrotorplugin target_link_libraries section.
=> Issue #79: Solved colorspacesmm issue on quadrotor plugins

src/stable/components/gazeboserver/plugins/kinect/kinectPlugin.cc
RgbdViewer crashes after throwing NullHandleExecption with kinect plugin. See [here](http://jderobot-developer-list.2315034.n4.nabble.com/JdeRobot-rgbdViwer-won-t-run-after-throwing-an-exception-td4642690.html) for more discussions.
=> Fix #119: RgbdViewer crashes with kinect plugin

CMakeLists.txt
The installation overrides the __init__.py file with other empty from 
```
src/stable/interfaces/python/jderobot/RoboCompJointMotor/
```
=> fixed an override of the __init__.py file on the installation process

src/stable/components/introrob/gui.cpp
Initially I used the method explained here to extract the angle of the pioneer model: http://stackoverflow.com/questions/5782658/extracting-yaw-from-a-quaternion
I realized later that for some cases, this method returns the opposite of the required angle. That was because the function acos returns an angle between [ 0; pi ], and maybe the correct angle is actually in the range [pi; 2*pi]. In this version I extract the desired angle, just like it is done in the gazebo::Quaternion:GetAsEuler() method
=> Introrob Pose3D fix

CMakeLists.txt
Just some reminders:
* CMAKE_BINARY_DIR == pwd of cmake
* CMAKE_SOURCE_DIR == cmake target dir
So cmake . --> CMAKE_BINARY_DIR==CMAKE_SOURCE_DIR
But not cmake ..
----
Related to #206 
This change should be validated by @chanfr
=> fix #206: install from binary dir

CMakeLists.txt, src/stable/components/gazeboserver/CMakeLists.txt, src/stable/interfaces/CMakeLists.txt, src/stable/interfaces/slice/jderobot/body.ice, src/stable/interfaces/slice/jderobot/bodyencoders.ice, src/stable/interfaces/slice/jderobot/bodymotors.ice, src/stable/interfaces/slice/jderobot/bodymovements.ice, src/stable/interfaces/slice/jderobot/camera.ice, src/stable/interfaces/slice/jderobot/common.ice, src/stable/interfaces/slice/jderobot/encoders.ice, src/stable/interfaces/slice/jderobot/genericData.ice, src/stable/interfaces/slice/jderobot/image.ice, src/stable/interfaces/slice/jderobot/laser.ice, src/stable/interfaces/slice/jderobot/motors.ice, src/stable/interfaces/slice/jderobot/namingService.ice, src/stable/interfaces/slice/jderobot/naofollowball.ice, src/stable/interfaces/slice/jderobot/naomotions.ice, src/stable/interfaces/slice/jderobot/pose3d.ice, src/stable/interfaces/slice/jderobot/pose3dencoders.ice, src/stable/interfaces/slice/jderobot/pose3dmotors.ice, src/stable/interfaces/slice/jderobot/ptencoders.ice, src/stable/interfaces/slice/jderobot/ptmotors.ice, src/stable/interfaces/slice/jderobot/remoteCloud.ice, src/stable/interfaces/slice/jderobot/sonars.ice, src/stable/interfaces/slice/jderobot/varcolor.ice, src/stable/interfaces/slice/jderobot/wiimote.ice
*Refer to #236*
* gazeboserver/plugins
* src/stable/interfaces
* Use `${CMAKE_CURRENT_BINARY_DIR}` for all generated objects
* Use correct namespaces for .ice files
from:
```
#include <common.h>
module jderobot {
```
to:
```
#include <jderobot/common.h>
module jderobot {
```
Therefore, `include_directories()` must only include cpp root (maintain old for backward compatibility)
* Full rewrite of slice2xx to allow complex hierarchies (modules==file tree)
* slice2py syntax is odd. It realizes a flattened generation plus hierarchical `__init__.py`
By the way, same problem was happening before, so it maintains exactly same format than before.
* module hierarchy is weird, (refer to java tree), interface **jointmotor** is not part of *jderobot*
```
module RoboCompJointMotor{
```
instead of
``` …
```
=> Outsource build (2): interfaces + gazeboserver/plugins

src/stable/libs/progeo/progeo.c, src/stable/libs/progeo/progeo.h
Details here: https://github.com/RoboticsURJC/JdeRobot/issues/16
This will solve a warning while compiling progeo library and a possible bug using pointers. Maybe in C++ it will work, we don't need to test it because progeo.c code is pure C, not C++ but it's possible that components using progeo needs `extern "C"` clause if they are programmed in C++.
=> Fix #16: C interface and fix pointer in progeo

buildpresets.cmake, src/stable/components/gazeboserver/models/flyingKinect/model.sdf, src/stable/components/gazeboserver/models/flyingKinect2/model.config, src/stable/components/gazeboserver/models/flyingKinect2/model.sdf, src/stable/components/gazeboserver/plugins/flyingKinect2/CMakeLists.txt, src/stable/components/gazeboserver/plugins/flyingKinect2/flyingKinect2.cfg, src/stable/components/gazeboserver/plugins/flyingKinect2/src/kinect.cc, src/stable/components/gazeboserver/plugins/flyingKinect2/src/pointcloudi.hpp, src/stable/components/gazeboserver/worlds/flyingkinect.world
The yet simple and minimal rewrite of flyingKinect.
* Single trigger: using root camera sensor to use sensor's `ConnectUpdate()`
* Single plugin: use ModelPlugin + SensorManager to gather any sensor
* Pose3D interface is embedded into plugin
- *embed rest interfaces is not as simple due Ice limitations*
* **Uses quadrotor2's push camera.**
- No more redefinition of jderobot::Camera
* Uses easyiceconfig
* No dedicated thread for Ice. It is no needed!
* PointCloud interface
- Same behavior as previous plugin: do nothing, dummy code
=> flyingKinect2

CMakeLists.txt, src/stable/components/basic_server/CMakeLists.txt, src/stable/components/followBall/CMakeLists.txt
* all components should now respect outsource build
* followBall
* basic_server
* improve cmake rule that install executables at /usr/local/bin
* this rule is NOT correct due it install files that could be blacklisted, but change it is not trivial.
=> Outsource build (3): last components

CMakeLists.txt, scripts/incremental_releases/incremental-releases.cmake, scripts/incremental_releases/version-upgrader.sh
*Related to #268*
Minimal Test:
1. Simple `cmake ..` to ensure it is working
2. Check `.deb` generated by metapackages
3. `make package` and check it
A. Real case usage I:
1. cmake or make package and push .deb to repo
2. repeat x2 and see incremental rc
B. Real case usage II:
1. Change major/minor/patch
2. cmake and check suffix == `-rc1`
C. Test script bounds I:
1. do by hand a x.y.z-rc9 and rc10
2. push both into repo
3. cmake to see if versioning number is respected
- wrong result: -rc10
- success result: -rc11
D. Test script bounds II:
1. Change manually `CPACK_DEBIAN_PACKAGE_VERSION`
2. See what happens. Expected:
- warning but ok
- version is unchanged
=> incremental releases

buildpresets.cmake
*Completeness for #264*
* **build_purge**, the alternative to delete cache
* better cache handling
* rewrite project name no longer requires remove cache
* fix build_all flag
* more explaining comments
1. cmake -Dbuild_x=ON -Dbuild_y=ON [...] --> initial cmake (creates cache)
2. cmake -Dbuild_z=ON [...] --> configure it a little bit more
3. make --> builds x,y,z
If you want to build another think, you MUST delete CMakeCache, but no longer with build_purge:
4. cmake -Dbuild_purge=ON --> disable every build_x; even stronger that remove cache
5. cmake -Dbuild_a=ON -Dbuild_b=ON [...] --> like initial cmake call
6. make --> builds a,b
=> build aliases (2): major improvements and fixes

src/stable/drivers/CMakeLists.txt, src/stable/tools/CMakeLists.txt
Related with #234, new folders added.
=> [issue 234] Added directories for the new code distribution

src/stable/components/gazeboserver/worlds/ArDrone.world, src/stable/components/uav_viewer/uav_viewer_simulated.cfg
Updated the configuration file to uav_viewer component and ArDrone.world. Now this world and uav_viewer work with quadrotor2 plugin.
=> Issue #328: Updated ArDrone.world and uav_viewer configuration file

src/stable/components/gazeboserver/plugins/pioneer/motors.cc, src/stable/components/gazeboserver/plugins/turtlebot/motors.cc, src/stable/components/kobukiViewer/gui/gui.cpp, src/stable/components/kobukiViewer/gui/gui.h, src/stable/components/kobukiViewer/gui/widget/controlvw.cpp, src/stable/components/kobukiViewer/gui/widget/controlvw.h
By now the configuration of the maximum linear and angular velocity offered by kobukiViewer are:
* **linear: 5 m/s** (18 km/h or 11,18 mph)
* **angular: 0.5 rad/s** (28,64 deg/s)
Drivers to change: 
Clients to change:
=> [issue #337] Absolute interfaces for: kobukiViewer, turtlebot motors.

CMakeLists.txt, scripts/metapackages/jderobot-deps-dev.info.in, scripts/metapackages/jderobot-deps.info.in
jderobot-deps-dev must not adquire *-rcX* suffix.
If deps changes, then version should be roll up to catch and notify this change.
changeset include some improvements at debian/control files.
See commits for more info.
*tags: enhance, aptitude*
=> metapackages: better name and version

src/stable/drivers/gazeboserver/models/whiteTaxi/model.sdf, src/stable/drivers/gazeboserver/models/yellowTaxi/model.sdf
Now both taxi models will work. The imuplugin still need revision, as it should not be necessary.
=> Solving issue #455: Taxi models are fixed.

CMakeLists.txt
This should fix the issue #463 by adding in a explicit form the new paths to be taken into account. This fix could be revised a posteriori to make simpler the manipulation of these paths( i.e. : path variable with loop, path discovering...).
=> [Issue #463] Includes new paths to the install generation step in CMake

Deps/opengl/CMakeLists.txt
Should fix the issue #452 according to the suggestion of checking first the list for `NOTFOUND` before trying to link the paths and making the finding check user output  consistent.
Also corrects the usage of the deprecated variables.
=> [Issue #452] Fixes CMake checks and output for OpenGL and GLUT.

src/stable/components/followBall/CMakeLists.txt, src/stable/components/recorder/CMakeLists.txt, src/stable/components/remoteConfiguration/CMakeLists.txt, src/stable/components/replayer/CMakeLists.txt, src/stable/components/teleoperator/CMakeLists.txt, src/stable/drivers/gazeboserver/plugins/flyingKinect/CMakeLists.txt, src/stable/drivers/gazeboserver/plugins/flyingKinect2/CMakeLists.txt, src/stable/drivers/gazeboserver/plugins/kinect/CMakeLists.txt, src/stable/tools/cameraview/CMakeLists.txt, src/stable/tools/naoviewer/CMakeLists.txt, src/stable/tools/recorder2/CMakeLists.txt, src/stable/tools/replayController/CMakeLists.txt, src/stable/tools/replayer2/CMakeLists.txt, src/stable/tools/rgbdViewer/CMakeLists.txt
[Issue #435]
This solves - at least partially - the CMAKE_CXX_FLAGS by prepending the current value to the new.
Also removes a "-std=c++0x", which conflicts with compilers that use only "-std=c++11" or can't use both at the same time; this flag is managed by another CMakeLists.txt anyway.
=> [Issue #435] Quick-fixes CMAKE_CXX_FLAGS resetting. Removes direct c++0x asignment.

CMakeLists.txt
Fixes issue #465.
According to Section "5.6.13 Description" of Debian Policy Manual, this commit reinserts the blank spaces of each line in the extended part of the description.
=> [Issue #465] Adds blank spaces on package extended description.

Deps/openni/CMakeLists.txt
This fix sets the preprocessor macro `i386` when the macro `__i386__` is detected, making XiPlatform.h work as intended for x32 linux platforms.
Also outputs a CMake warning as this _fix_ could affect to an hypotetical code using that macro.
=> [Issue #468] Quick-fix for x32 openni related components.

src/stable/drivers/laser_server/CMakeLists.txt, src/stable/drivers/laser_server/hokuyo/hokuyo.cpp, src/stable/drivers/laser_server/hokuyo/hokuyo.h, src/stable/drivers/laser_server/hokuyo/hokuyomanager.cpp, src/stable/drivers/laser_server/hokuyo/hokuyomanager.h, src/stable/drivers/laser_server/laser_server.cfg, src/stable/drivers/laser_server/laseri.cpp, src/stable/drivers/laser_server/laseri.h, src/stable/drivers/laser_server/lasermanager.h, src/stable/drivers/laser_server/main.cpp
I've created the Hokuyo laser driver. (#449).
laser_server supports future expansions of new lasers: 
- Creating a class that inherits from **laserManager** as **hokuyoManager**
- In the configuration file, _**Laser.Model**_ identifies the model of laser to use.
- In laseri.cpp, adding a case more to the constructor "if"
=> [issue #449] Created laser_server for Hokuyo laser

Deps/boost/CMakeLists.txt, Deps/pcl/CMakeLists.txt
Fixes issue #467 for boost and pcl libraries. 
Important notes:
* This fix works for a dpkg-based system and for libraries installed from a package, as it uses this command to find which package installed which file.
* This fix uses undocumented CMake variables inside `FindBoost.cmake`and `FindPCL.cmake` in order to make easier and quick the search task. Any upstream changes to these files could break this fix.
* This fix checks for the existence of the commands needed before performing the search; for systems without these commands, a CMake warning is issued telling the user to check any package made via CPack and that the normal build will not be affected.
=> [Issue #467] Add dpkg package name discovery for boost and pcl.

src/stable/tools/replayer2/replayer.cpp
This two replayer threads were out of sync because they were executing at 1 Hz. Issue #441
=> [Issue #441] Replayer Pose3D and Pose3DEncoders threads sync

src/stable/drivers/gazeboserver/models/whiteTaxi/model.sdf, src/stable/drivers/gazeboserver/models/yellowTaxi/model.sdf
This pull request should fix #493 for the following models:
- yellowTaxi
- whiteTaxi
=> Gazebo models with plugin absolute paths: yellow and white Taxi

Deps/boost/CMakeLists.txt
Some lines regarding the static variable injection weren't removed in the last pull request about this issue (PR #488), making Debian Packages again to have wrong dependency chain.
This pull request should fix this bug.
=> [Issue #467] Fixes package discovery for boost

src/drivers/MAVLinkServer/MAVLinkServer.py, src/drivers/ardrone_server/CMakeLists.txt, src/drivers/ardrone_server/src/ardrone_driver.cpp, src/drivers/ardrone_server/test/print_gps_data.cpp, src/drivers/basic_server/CMakeLists.txt, src/drivers/basic_server/basic_server.cpp, src/drivers/kinect2server/CMakeLists.txt, src/drivers/kinect2server/kinect2Server.cpp, src/drivers/kobuki_driver/CMakeLists.txt, src/drivers/kobuki_driver/main.cpp, src/drivers/pclRGBDServer/CMakeLists.txt, src/drivers/pclRGBDServer/kinectServer.cpp, src/libs/easyiceconfig_cpp/src/loader.cpp, src/libs/easyiceconfig_py/easyiceconfig/easyiceconfig.py, src/tools/namingService/CMakeLists.txt, src/tools/namingService/main.cpp, src/tools/recorder2/CMakeLists.txt, src/tools/recorder2/recorder2.cpp, src/tools/visualHFSM/generate.cpp
This pull request allow us to run JdeRobot components (tools, clients or generated with visualHFSM) with o without Ice.Config flag.
Two forms are accepted:
`cameraserver cameraserver.cfg`
`cameraserver --Ice.Config=cameraserver.cfg`
only it has 3 exceptions, Nao client and server an girafferServer because are deprecated
=> [#524] Added EasyIce to all components except nao* giraffeServer

CMakeLists.txt, src/libs/resourcelocator/CMakeLists.txt, src/libs/resourcelocator/include/resourcelocator/gladelocator.hpp.in
This PR should fix the issue #485 **only** for resourcelocator.
Note this PR is intended to be applied only if PR #530 is accepted, please check it first.
=> [Issue #485] Refactor resourcelocator to use CMAKE_INSTALL_PREFIX

src/libs/easyiceconfig_py/easyiceconfig/hardcodedpaths.py.in
This PR prepares to Python clients of Jderobot to Windows.
In Windows we already use Ice 3.6 because it was very difficult to install 3.5 and will soon jump to Ice 3.6
**1. Download Dependences:**
Download python 2.7.12 and install checked env variables (Is posible that you need restart to run the PATH):  
https://www.python.org/ftp/python/2.7.12/python-2.7.12.amd64.msi 
 
Download qt 4.8.7:  
http://download.qt.io/official_releases/qt/4.8/4.8.7/qt-opensource-windows-x86-vs2010-4.8.7.exe 
Download github Desktop:
https://desktop.github.com/
 
update pip: 
<pre>python -m pip install --upgrade pip </pre>
Install deps: 
<pre>pip install numpy zeroc-ice 
pip install http://jderobot.org/store/aitormf/uploads/windows/opencv_python-3.1.0-cp27-cp27m-win_amd64.whl  …
=> [Issues #419 #420] Support for Windows

src/libs/depthLib/CMakeLists.txt, src/libs/easyiceconfig_cpp/include/easyiceconfig/stdutils.hpp, src/libs/fuzzylib/CMakeLists.txt, src/libs/geometry/CMakeLists.txt, src/libs/jderobotHandlers/CMakeLists.txt, src/libs/jderobotViewer/CMakeLists.txt, src/libs/jderobotutil/CMakeLists.txt, src/libs/log/CMakeLists.txt, src/libs/ns/CMakeLists.txt, src/libs/parallelIce/CMakeLists.txt, src/libs/pioneer/CMakeLists.txt, src/libs/resourcelocator/include/resourcelocator/stdutils.hpp, src/libs/xmlParser/CMakeLists.txt
Solved problem installing dynamic libraries with Cmake 3.5. 
IMPORTANT NOTE: some libs versions have been removed due to cpack doesn't link some of them when building the package. Please @chanfr check this.
=> [issue #562] Updated CMakeLists of various libs

scripts/docker/gazebo/gzserver/Dockerfile, scripts/docker/gazebo/gzserver/gzserver_entrypoint.sh, scripts/docker/jderobot/base/Dockerfile, scripts/docker/jderobot/gzweb/Dockerfile, scripts/docker/jderobot/gzweb/installGzweb.sh
Updated Dockerfiles to use Jderobot 5.4.1.
- I've had to create a Docker for **gazebo7 with Ubuntu Xenial** (16.04) because before we used oficial gazebo7 docker but this is with Trusty (14.04).
- **Jderobot:base** not needs compile JdeRobot, now use oficial package
- **Jderobot:gzweb** have been updated from gzweb 1.3 to gzweb 2.0
=> [issue #599] Updated Dockerfiles to use Jderobot 5.4.1

src/tools/kobukiviewerjs/public/js/api_workers/motors_worker.js, src/tools/kobukiviewerjs/public/js/api_workers/pose3d_worker.js, src/tools/uavviewerjs/public/js/api_workers/pose3d_worker.js
The problem was that in the jump from beta version of IceJS to 3.6.3, there are some dependencies of some interfaces that have become obligatories
=> [issue #629] Solved bug in KobukiViewerJS and UavVieweJS

src/drivers/gazeboserver/plugins/f1/laser.cc, src/drivers/gazeboserver/plugins/turtlebot/include/turtlebot/turtlebotsensors.hh, src/drivers/gazeboserver/plugins/turtlebot/src/interfaces/laseri.cpp, src/drivers/gazeboserver/plugins/turtlebot/src/turtlebotsensors.cc, src/drivers/laser_server/hokuyo/hokuyomanager.cpp, src/interfaces/slice/jderobot/laser.ice, src/tools/kobukiViewer/CMakeLists.txt, src/tools/kobukiViewer/gui/widget/glwidget.cpp, src/tools/kobukiViewer/gui/widget/glwidget.h, src/tools/kobukiViewer/gui/widget/laserwidget.cpp, src/tools/kobukiViewer/gui/widget/laserwidget.h, src/tools/kobukiViewer/robot/sensors.cpp, src/tools/kobukiViewer/robot/sensors.h, src/tools/kobukiViewer/robot/types.h, src/tools/kobukiviewerjs/public/js/api_workers/laser_worker.js, src/tools/kobukiviewerjs/public/js/jderobot/laser.js, src/tools/recorder2/poolWriteLasers.cpp, src/tools/recorder2/poolWriteLasers.h, src/tools/replayer2/replayer.cpp
I have modified laser interface to following:
<pre>
Laser {
int[] data
int numLaser
float min_angle
float max_angle
float max_range
float min_range
time_stampt
}
</pre>
and I have adapted all C++ components to use it
This PR resolves #652
=> [Issue #652] Modified laser Interface

Deps/vtk/CMakeLists.txt
We no longer add it to the list of dependencies, but I leave it in the directory because we need to know with which we compile
=> [issue #663] deleted vtk of dependecy list.

Deps/vtk/CMakeLists.txt
We no longer add it to the list of dependencies, but I leave it in the directory because we need to know with which we compile
=> [issue #663] deleted vtk7 of dependecy list.

CMakeLists.txt, Deps/eigen3/CMakeLists.txt, Deps/gsl/CMakeLists.txt, Deps/ros/CMakeLists.txt, src/libs/jderobotcomm_cpp/CMakeLists.txt, src/libs/jderobotcomm_cpp/package.xml
Moved all depencencies to Deps (#695)
=> [Issue #695] Moved all depencencies to Deps

src/tools/basic_component_py/CMakeLists.txt, src/tools/basic_component_py/basic_component_py.in
Added launcher to basic_component_py
Now, after installing, you can launch basic_component_py using:
<pre>
basic_component_py basic_component_py.cfg
</pre>
fix #749
=> [issue #749] Added launcher to basic_component_py

src/tools/uav_viewer_py/CMakeLists.txt, src/tools/uav_viewer_py/uav_viewer_py.in
Added Launcher to uav_viewer_py
Now, after installing, you can launch uav_viewer_py using:
<pre>
uav_viewer_py uav_viewer_py.cfg
</pre>
fix #750
=> [issue #750] Added Launcher to uav_viewer_py

src/tools/uav_viewer/gui/mainwindow.cpp, src/tools/uav_viewer/sensors/sensors.cpp, src/tools/uav_viewer/sensors/sensors.h, src/tools/uav_viewer/uav_viewer.cfg, src/tools/uav_viewer/uav_viewer_simulated.cfg
this PR solves #833
the problem was that atof doesn't work well, truncates the decimal part
=> [issue #833] Solved problem with max values of cmdvel in uav_viewer

src/drivers/gazeboserver/worlds/reconstruccion3D.world
The objects in the images from the robot cameras are too dark and so, the image processing to estimate 3D data is not feasible.
=> Lights are needed in the 3D_reconstruction world #853

src/tools/pantilt_teleop_py/gui/cameraWidget.py, src/tools/pantilt_teleop_py/pantilt_teleop.cfg, src/tools/pantilt_teleop_py/pantilt_teleop.py
Pantilt_teleop now use jderobotcomm instead of parallelce for camera interface.
Finally, as Evi_cam uses v4l as a driver I have decided to use the Ros Usb_cam driver to serve the images instead of make a server.
[video](https://www.youtube.com/watch?v=wYvz57oRFU0)
=> [issue #845] Pantilt_teleop now use jderobotcomm for camera

scripts/docker/build_dockers.py, scripts/docker/docker_list.yaml, scripts/docker/jderobot/dev-only-ice/Dockerfile, scripts/docker/jderobot/dev-only-ice/testPR, scripts/docker/jderobot/dev/Dockerfile, scripts/docker/jenkins/dev/Dockerfile, scripts/docker/jenkins/dev/compile.sh
Updated Dockerfiles and added python script to generate all docker containers.
python script needs **python-yaml** package and **docker** pip package installed. With **_docker_list.yaml_** file you can configure which docker will be builded and pushed
to use the script run in  **jderobot/scripts/docker/** : 
`
python build_dockers.py docker_list.yaml
`
=> [Issue #884] Updated Dockerfiles

src/tools/cameraview_py/CMakeLists.txt, src/tools/cameraview_py/cameraview.py, src/tools/cameraview_py/cameraview_py.cfg, src/tools/cameraview_py/cameraview_py.in
The following code changes were done for #887 and #888: 
- added a file cameraview.in which contains the cmake install prefix as follows: 
`#!/bin/bash`
`python @CMAKE_INSTALL_PREFIX@/share/jderobot/python/cameraview_py/cameraview.py $*`
- using the CMakeLists.txt of basic_component_py, I wrote a CMakeLists.txt file for cameraview_py
- the IP address contained in the file cameraview_py.cfg was changed to: 
`Camera.Proxy = cameraA:default -h 192.168.1.16 -p 9999`
- after successfully installing cameraview_py, I started cameraserver and ran camerview_py. I noticed that the colour space used by camerview_py was BGR instead of RGB. To resolve this I have added the following line in the file cameraview.py: 
`image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)`
=> [Issue  #887 and #888]: resolving cameraview_py installation and BGR color space

src/libs/comm_cpp/CMakeLists.txt, src/libs/comm_cpp/include/jderobot/comm/ice/rgbdIceClient.hpp, src/libs/comm_cpp/include/jderobot/comm/interfaces/rgbdClient.hpp, src/libs/comm_cpp/include/jderobot/comm/rgbdClient.hpp, src/libs/comm_cpp/include/jderobot/comm/ros/translators.hpp, src/libs/comm_cpp/src/ice/rgbdIceClient.cpp, src/libs/comm_cpp/src/rgbdClient.cpp, src/libs/comm_cpp/src/ros/translators.cpp, src/libs/comm_py/comm/ice/rgbdIceClient.py, src/libs/comm_py/comm/rgbdClient.py.only-ice.in, src/libs/comm_py/comm/rgbdClient.py.ros.in, src/libs/comm_py/comm/ros/listenerCamera.py, src/samples/basic_component_py/basic_component_py.yml, src/types/cpp/include/jderobot/types/rgbd.h, src/types/python/jderobotTypes/__init__.py, src/types/python/jderobotTypes/rgbd.py
This PR adds support for ROS Depth image to Comm cameraClient and Synchronized Rgbd data (only in ICE) to Comm library
=> [issue #913] added support for RGBD sensors in Ice to comm

src/tools/visualStates_py/gui/cppgenerator.py
Uses interface name as the header mapping during cpp code generation and solves #923
=> use interface name as the header mapping key fixes #923

test/packages/.gitignore, test/packages/README.md, test/packages/cameraview/Dockerfile, test/packages/cameraview/files.txt, test/packages/cameraview/search_files.sh, test/packages/install_test/Dockerfile, test/packages/run_test.py, test/packages/test_list.yml, test/packages/update_test/Dockerfile
I've created 3 tests at the moment:
* For install and uninstall jderobot package in a clean docker
* For update fron last version to new version
* For cameraview package, that install the package and search all files that should have the package 
to run this tests only need go to jderobot_folder/test/packages, install docker python api and run the tests:
```sh
$ pip install docker
$ python run_test.py test_list.yml
```
=> created test for packages

Deps/yaml-cpp/CMakeLists.txt, src/tools/scratch2jderobot/CMakeLists.txt
added required clause to yaml-cpp and solved bug in scratch2jderobot  CMakeLists
=> [#967 & #952] yaml-cpp required and bug in scratch2jderobot

src/tools/visualStates_py/gui/treemodel.py, src/tools/visualStates_py/gui/visualstates.py
Fixes the bug that does not remove states from tree view when new state machine is created. Also, it fixes the bug that occurs when trying to remove a state.
=> [tools] [visualstates] create new state machine does not remove items

src/drivers/YoutubeServer/CMakeLists.txt, src/drivers/YoutubeServer/JdeRobot/ImageProviderI.py, src/drivers/YoutubeServer/config.yml, src/drivers/YoutubeServer/videoTools/processVideo.py, src/drivers/YoutubeServer/videoTools/threadFlow.py, src/drivers/YoutubeServer/youtubeServer.py, src/drivers/YoutubeServer/youtubeserver.in, src/drivers/YoutubeServer/youtubeserver.py, src/drivers/YoutubeServer/youtubeserver.yml
Now Youtubeserver works for python2.7. The Framerate is still low but we will improve it in future iterations. Also you can kill the program with Ctrl+c, you could not do that before.
=> Added support to YoutubeServer for python2.7

src/tools/rgbdViewer/freenect_ros.yml
=> [#1071] Create freenect_ros.yml

src/interfaces/slice/jderobot/visualization.ice
Modification in the JdeRobot interface, visualization.ice, to be able to connect the new viewer with the 3Drecontrunction practice of Academy.
A new RGBSegments class (segment + color) and two sequences have been created to create the point and segment sending buffers. In addition, two new functions that return these buffers are added.
=> issue #1121 Modify the ice interface of JdeRobot to work with 3DViewer-web

assets/gazebo/worlds/nurburgrinLineROS.world
This pull-request add more light and use the f1_renault model in the Nurburgrin circuit. Fixes the #1335 issue.
=> Updated Nurburgrin world with light

Deps/boost/CMakeLists.txt
Was having this error while compiling Jderobot project:
"Error:string sub-command REGEX, mode REPLACE needs at least 6 arguments total to command"
In line 23 of Deps/boot/CMakeLists.txt
changed
string(REGEX REPLACE "^([^:]+):.*" \\1 _PKG ${_PKG})
to 
string(REGEX REPLACE "^([^:]+):.*" \\1 _PKG "${_PKG}")
Adding **double quotes** solved the compilation issue.
=> Updated CMakeLists.txt

src/interfaces/CMakeLists.txt
Fixes #1373 : When #1370  was merged, the entry in the CMakeLists for JdeRobotKids.py was not deleted. This results in an error in the sudo make install command. This pull request fixes the error by removing the entry for JdeRobotKids.py
=> Removed entry for JdeRobotKids.py

src/drivers/turtlebot_ws/build_turtlebot2.sh
For now, there's only a script that does all the work. It's the easiest way to install the turtlebot for gazebo. The script is based on this one: https://github.com/gaunthan/Turtlebot2-On-Melodic/blob/master/install_basic.sh
@pankhurivanjani you can test it whenever you want :) and if you require more documentation let me know and I will upload a little how to.
=> [Issue #1380] Added support for turtlebot2 in base

README.md
it is essential for all Ubuntu distros not specifically 16
=> remove for Ubuntu 16 sentence
