JdeRobot/base

CMakeLists.txt

Fixed #5 by making the python/jderobot directory using CMake macros

---

src/stable/libs/geometry/progeo/Progeo.cpp

Details here: https://github.com/RoboticsURJC/JdeRobot/issues/23

Fix #23: Unused variables in Progeo::saveToFile

---

.gitignore

Details here: https://github.com/RoboticsURJC/JdeRobot/issues/19
This is my proposal for a minimal .gitignore file to avoid dozens of untracked files every status or commit.

Fix #19: Proposal for a minimal .gitignore file

---

src/stable/components/namingService/NamingServiceJdeRobot.cpp

Details here: https://github.com/RoboticsURJC/JdeRobot/issues/25

Fix #25: Missing return value (bool) in NamingServiceJdeRobot::load

---

README.md

Show the build status of Jenkins CI on the Github page directly.

add the Jenkins build status

---

README.md

We may should have a standard workflow for development for better collaborate. Also, this is a pull request demoing for fixing #13.

Fix #13 - Add a How To Contribute section

---

README.md

Make the README file more clear and readable.

fix some typos and style refactor using Markdown list

---

CMakeLists.txt
src/stable/interfaces/slice/jderobot/CMakeLists.txt

Details here: https://github.com/RoboticsURJC/JdeRobot/issues/37

Fix #37: Included Java interfaces generation to cmake chain

---

src/stable/components/gazeboserver/CMakeLists.txt
src/stable/components/gazeboserver/plugins/refereeplugin/CMakeLists.txt
src/stable/components/gazeboserver/plugins/refereeplugin/referee.cc
src/stable/components/gazeboserver/plugins/refereeplugin/referee.hh
src/stable/interfaces/slice/jderobot/referee.ice

Hello.
I've added the refereeplugin files for the quadrotor programming contest in gazeboserver/plugins directory along with the CMakeLists.txt file. There is also the corresponding slice file in the interfaces directory.
Regards,
Daniel

Referee plugin for quadrotor programming contest

---

Deps/opencv/CMakeLists.txt

Added a missing dependency update for opencv 2.4 in Deps

Updated opencv Deps to the last stable version 2.4

---

src/stable/components/gazeboserver/plugins/quadrotor/ardroneplugin.cfg
src/stable/components/gazeboserver/plugins/quadrotor/imuplugin.cfg
src/stable/components/gazeboserver/plugins/quadrotor/quadrotorplugin.cc
src/stable/components/gazeboserver/plugins/quadrotor/quadrotorplugin.hh

Code changed to solve the #74 issue. Noise generation goes in the OnUpdate function instead of setVelocityCommand.

Solved noise generation error in quadrotor drivers

---

src/stable/components/gazeboserver/plugins/quadrotor/ardroneplugin.cfg
src/stable/components/gazeboserver/plugins/quadrotor/imuplugin.cfg
src/stable/components/gazeboserver/plugins/quadrotor/quadrotorplugin.cc
src/stable/components/gazeboserver/plugins/quadrotor/quadrotorplugin.hh

The cfg files needed to create the ICE interfaces are now in the quadrotor drivers directory

Issue #78: Configuration files added

---

src/stable/components/gazeboserver/models/ArDrone/model.sdf
src/stable/components/gazeboserver/models/RedArDrone/model.sdf

I have removed the gps sensor declaration in the model.sdf file of ArDrone and RedArDrone.

Issue #96: ArDrone models no longer calls gpsplugin

---

src/stable/components/gazeboserver/plugins/flyingKinect/CMakeLists.txt
src/stable/components/gazeboserver/plugins/flyingKinect/clean.sh
src/stable/components/gazeboserver/plugins/flyingKinect/flyingKinect.cfg
src/stable/components/gazeboserver/plugins/flyingKinect/flyingKinectPose3d.cfg
src/stable/components/gazeboserver/plugins/flyingKinect/kinect.cc
src/stable/components/gazeboserver/plugins/flyingKinect/kinect.cfg
src/stable/components/gazeboserver/plugins/flyingKinect/kinect.h
src/stable/components/gazeboserver/plugins/flyingKinect/pose3d.cc
src/stable/components/gazeboserver/plugins/flyingKinect/pose3d.h
src/stable/components/gazeboserver/plugins/flyingKinect/sharer.cc
src/stable/components/gazeboserver/plugins/flyingKinect/sharer.h

This plugin provides RGBD data and allow to move the 3D position of the simulated sensor in the Gazebo world.
Also, this is a pull request related with issue #100.

[jnbosgos] Add new plugin flyingKinect.

---

src/stable/components/navigatorCamera/CMakeLists.txt
src/stable/components/navigatorCamera/gui.cpp
src/stable/components/navigatorCamera/gui.h
src/stable/components/navigatorCamera/navigatorCamera.cfg
src/stable/components/navigatorCamera/navigatorCamera.cpp
src/stable/components/navigatorCamera/navigatorCamera.glade
src/stable/components/navigatorCamera/quaternion.h
src/stable/components/navigatorCamera/sharer.cpp
src/stable/components/navigatorCamera/sharer.h

This component allows teleoperate a simulated camera or RGBD sensor that has a Pose3D interface, like the flyingKinect plugin.
More info about this component in http://jderobot.org/Jnbosgos#Navigator_Camera.

[jnbosgos] Add navigatorCamera component.

---

src/stable/components/refereeViewer/refereeViewer.py

Minor change for refereeViewer so it will stop displaying a debbuging message.
I forgot to delete it.

Referee Viewer minor change

---

src/stable/components/gazeboserver/models/pioneer2dxJde/model.sdf
src/stable/components/gazeboserver/plugins/pioneer/CMakeLists.txt
src/stable/components/gazeboserver/plugins/pioneer/pioneer2dxPose3D.cfg
src/stable/components/gazeboserver/plugins/pioneer/pose3d.cc
src/stable/components/gazeboserver/plugins/pioneer/pose3d.h
src/stable/components/introrob/API.cpp
src/stable/components/introrob/API.h
src/stable/components/introrob/control.cpp
src/stable/components/introrob/control.h
src/stable/components/introrob/gui.cpp
src/stable/components/introrob/gui.h
src/stable/components/introrob/introrob.cfg
src/stable/components/introrob/introrob.cpp

Warning: if you copied the pioneer model.sdf in ~/.gazebo/models, as instructed in: (http://jderobot.org/Teaching_robotics_with_jderobot#2013-2014_courses), you also need to copy the new model there.

Introrob gazeboserver Pose3D interface

---

src/stable/components/gazeboserver/models/carColorBeacon/model.sdf
src/stable/components/gazeboserver/plugins/car/carMotors.cc

Added the movement fix for the cars plugin (motors.cc)

Fix #222 Complete pull request #228

---

src/stable/components/gazeboserver/models/turtlebotJde2cam/model.sdf
src/stable/components/gazeboserver/plugins/turtlebot/CMakeLists.txt
src/stable/components/gazeboserver/plugins/turtlebot/pose3d.cc
src/stable/components/gazeboserver/plugins/turtlebot/pose3d.h
src/stable/components/gazeboserver/plugins/turtlebot/turtlebotPose3D.cfg

Added the pose3D interface to the turtlebot in order to remove the encoders interface soon.

Turtlebot with pose3D interface instead of encoders

---

src/stable/libs/easyiceconfig_cpp/CMakeLists.txt
src/stable/libs/easyiceconfig_cpp/LICENSE
src/stable/libs/easyiceconfig_cpp/README.md
src/stable/libs/easyiceconfig_cpp/include/easyiceconfig/EasyIce.hpp
src/stable/libs/easyiceconfig_cpp/include/easyiceconfig/debug.hpp
src/stable/libs/easyiceconfig_cpp/include/easyiceconfig/hardcoredlocations.h
src/stable/libs/easyiceconfig_cpp/include/easyiceconfig/initializer.hpp
src/stable/libs/easyiceconfig_cpp/include/easyiceconfig/injector.hpp
src/stable/libs/easyiceconfig_cpp/include/easyiceconfig/loader.hpp
src/stable/libs/easyiceconfig_cpp/include/easyiceconfig/stdutils.hpp
src/stable/libs/easyiceconfig_cpp/src/demo/demo.cpp
src/stable/libs/easyiceconfig_cpp/src/demo/ice.cfg
src/stable/libs/easyiceconfig_cpp/src/initializer.cpp
src/stable/libs/easyiceconfig_cpp/src/loader.cpp
src/stable/libs/easyiceconfig_cpp/src/tests/test_loader.cpp
src/stable/libs/easyiceconfig_cpp/src/tests/test_stdutils.cpp
src/stable/libs/easyiceconfig_py/.gitignore
src/stable/libs/easyiceconfig_py/.idea/.name
src/stable/libs/easyiceconfig_py/CMakeLists.txt
src/stable/libs/easyiceconfig_py/LICENSE
src/stable/libs/easyiceconfig_py/README.md
src/stable/libs/easyiceconfig_py/demo.py
src/stable/libs/easyiceconfig_py/easyiceconfig/__init__.py
src/stable/libs/easyiceconfig_py/easyiceconfig/easyiceconfig.py
src/stable/libs/easyiceconfig_py/easyiceconfig/hardcoredpaths.py

easyiceconfig (py+cpp)

---

src/stable/components/cameraserver/cameraserver.cpp

* I have used Signals to solve the bug.
* 1 variable "flag" and 1 function "signalHandler" have been added . They are used to release capture whenever Ctrl-C signal is used.
Sir this is my first Pull Request ever, so I apologize in advance for any stupid mistakes that I may have created.
Thank You

#71 Camera Server blocks the the camera 

---

src/stable/components/colorTuner/colorTuner.cpp
src/stable/components/colorTuner/viewer.cpp
src/stable/components/colorTuner/viewer.h

Whole component has been changed.
This time cv::Mat has been used everywhere.

Renewing color tuner (colorTuner old image format #281)

---

src/stable/components/gazeboserver/models/ArDrone2/model.config
src/stable/components/gazeboserver/models/ArDrone2/model.sdf
src/stable/components/gazeboserver/plugins/quadrotor2/include/quadrotor/interfaces/pose3di.h
src/stable/components/gazeboserver/plugins/quadrotor2/include/quadrotor/quadrotorcontrol.hh
src/stable/components/gazeboserver/plugins/quadrotor2/src/interfaces/pose3di.cpp
src/stable/components/gazeboserver/plugins/quadrotor2/src/quadrotorcontrol.cc
src/stable/components/gazeboserver/plugins/quadrotor2/src/quadrotorcontrol_hector.cc
src/stable/components/gazeboserver/plugins/quadrotor2/src/quadrotorice.cc

quadrotor2 extra features

---

CMakeLists.txt
Deps/CMakeLists.txt
Deps/LoadJderobotDependencies.cmake

* Moves all Deps logic inside
* Using it from outside tested
* Minor cleanup
Closes #292 
* from inside: https://github.com/jderobot-varribas/JdeRobot/blob/dbba891c8c617b9b6b0e51fb4e6f919d1b8244a3/CMakeLists.txt#L117
* from outside: https://github.com/jderobot-varribas/JdeRobot-sandbox/blob/master/cmake/Deps/jderobot-deps/CMakeLists.txt

reusable Deps

---

src/stable/components/cameraserver/cameraserver.cfg

I have changed NamingService.Enabled in cameraserver.cfg to make it disabled by default. 
I have also changed the dafault value of CameraSrv.Camera.0.Uri because it gives an error otherwise.
Thank You

[issue 309] Changing default settings of Naming Service

---

src/stable/components/cameraview/CMakeLists.txt
src/stable/components/cameraview/viewer.cpp
src/stable/components/giraffeClient/CMakeLists.txt
src/stable/components/giraffeClient/controller.cpp
src/stable/components/introrob/CMakeLists.txt
src/stable/components/introrob/gui.cpp
src/stable/components/navigatorCamera/CMakeLists.txt
src/stable/components/navigatorCamera/gui.cpp
src/stable/components/navigatorCamera/navigatorCamera.cfg
src/stable/components/opencvdemo/CMakeLists.txt
src/stable/components/opencvdemo/viewer.cpp
src/stable/components/replayController/CMakeLists.txt
src/stable/components/replayController/replayControllerGui.cpp
src/stable/components/rgbdCalibrator/CMakeLists.txt
src/stable/components/rgbdCalibrator/viewer.cpp
src/stable/components/rgbdManualCalibrator/CMakeLists.txt
src/stable/components/rgbdManualCalibrator/controller.cpp
src/stable/components/rgbdViewer/CMakeLists.txt
src/stable/components/rgbdViewer/rgbdViewergui.cpp
src/stable/libs/resourcelocator/CMakeLists.txt
src/stable/libs/resourcelocator/include/resourcelocator/gladelocator.hpp
src/stable/libs/resourcelocator/include/resourcelocator/resourcelocator.hpp
src/stable/libs/resourcelocator/include/resourcelocator/stdutils.hpp
src/stable/libs/resourcelocator/src/resourcelocator.cpp
src/stable/libs/resourcelocator/src/test/test_gladelocator.cpp

from https://github.com/jderobot-varribas/resourcelocator.git

solve glade problem #263 with resourcelocator

---

src/stable/components/refereeViewer/refereeViewer.cfg
src/stable/components/refereeViewer/refereeViewer.py

Refactor refereeViewer to EaseIceConfig and ArDrone2 plugin

Issue #363: Refactor refereeViewer.

---

src/stable/components/gazeboserver/gazebo-setup.sh

gazebo-setup seems broken at rc7 (fc66a57).
I redo it for correctness and to solve any issues.
please, try to change branch name on merge.

fix broken gazebo-setup.sh

---

src/stable/drivers/gazeboserver/worlds/Actors_GrannyAnnie2.world

I've added Actors_GrannyAnnie2.world to gazeboserver/worlds folder

[Issue #448] Added Actors_GrannyAnnie2.world to gazeboserver worlds

---

src/stable/components/recorder/CMakeLists.txt
src/stable/components/recorder/recordergui.cpp
src/stable/components/recorder/recordergui.h
src/stable/components/replayer/CMakeLists.txt
src/stable/components/replayer/replayergui.cpp
src/stable/components/replayer/replayergui.h
src/stable/tools/colorTuner/colorTuner.cfg
src/stable/tools/recorder2/CMakeLists.txt
src/stable/tools/recorder2/recordergui.cpp
src/stable/tools/recorder2/recordergui.h
src/stable/tools/replayer2/CMakeLists.txt
src/stable/tools/replayer2/replayergui.cpp
src/stable/tools/replayer2/replayergui.h

Recorder and Replayer now use resourcelocator to locate glade files instead of manual route

[#issue458] fixed gui bug in recorder and replayer

---

src/stable/tools/uav_viewer/CMakeLists.txt
src/stable/tools/uav_viewer/gui/datawidget.cpp
src/stable/tools/uav_viewer/gui/datawidget.h
src/stable/tools/uav_viewer/gui/mainwindow.cpp
src/stable/tools/uav_viewer/gui/mainwindow.h
src/stable/tools/uav_viewer/gui/ui_mainwindow.h
src/stable/tools/uav_viewer/gui/velwidget.cpp
src/stable/tools/uav_viewer/gui/velwidget.h
src/stable/tools/uav_viewer/uav_viewer_simulated.cfg

Velocity dials are not working even in the previous version of the tool, Will be solved in another PR

[issue #442] Reduced uav_viewer GUI to be more usable

---

src/stable/tools/colorTuner/colorTuner_drone.cfg

I've created a config file to connect ColorTunner to ardrone_server (#497)

[issue #497] Created config file to connect ColorTunner to ardrone_server

---

src/stable/tools/basic_component_py/actuators/motors.py
src/stable/tools/basic_component_py/basic_component_py.cfg
src/stable/tools/basic_component_py/gui/cameraWidget.py
src/stable/tools/basic_component_py/main.py
src/stable/tools/basic_component_py/sensors/camera.py

When a interface of basic_component_py fails, it continues running.
Basic_component_py reads image format from cfg file.

[Issue #508] basic_component_py has optional interfaces

---

CMakeLists.txt.user
src/stable/tools/recorder2/poolWriteImages.cpp
src/stable/tools/recorder2/poolWriteImages.h
src/stable/tools/recorder2/recorder.cfg
src/stable/tools/recorder2/recorder2.cpp

fix imageFormat error (#486), now it supports same image formats than other componentes of JdeRobot

[issue #486] fix imageFormat error

---

src/stable/drivers/laser_server/hokuyo/hokuyomanager.cpp
src/stable/drivers/laser_server/hokuyo/hokuyomanager.h
src/stable/drivers/laser_server/laser_server.cfg
src/stable/drivers/laser_server/laseri.cpp

I've added face up option  to laser. to use it just to change this option in the cfg file

[Issue #506] added face up option to laser

---

scripts/docker/README.md
scripts/docker/jderobot/base/Dockerfile
scripts/docker/jderobot/base/README.md
scripts/docker/jderobot/base/base_entrypoint.sh
scripts/docker/jderobot/base/installJderobot.sh
scripts/docker/jderobot/gzweb/Dockerfile
scripts/docker/jderobot/gzweb/README.md
scripts/docker/jderobot/gzweb/gzweb_entrypoint.sh
scripts/docker/jderobot/gzweb/installGzweb.sh
scripts/docker/scripts/README.md
scripts/docker/scripts/delete-all.sh

I have added the dockerfiles in scripts/docker.
this PR resolves #549

Dockerfiles in JdeRobot

---

Deps/pcl/CMakeLists.txt

Updated dependencies for JdeRobot

[Issue #557] PCL 1.8

---

Deps/opencv/CMakeLists.txt
src/drivers/openniServer/openniServer.cpp

Updated dependencies for JdeRobot and solved include problems in OpenniServer

[issue #560] OpenCV 3.1

---

src/drivers/laser_server/main.cpp

[issue #577] Added EasyIce to laser_server

---

Deps/qfi/CMakeLists.txt

[issue #586] Added qfi to deps

---

src/interfaces/slice/jderobot/CMakeLists.txt

Solved import modules bug in jderobot interfaces. (issue #592)

[issue #592] Solved import modules bug in jderobot interfaces

---

src/drivers/kobuki_driver/kobukimanager.cpp
src/drivers/kobuki_driver/kobukimanager.h

Solved Pose3D position fail. (#507)
The problem was that in kobukimanager.h we forced to don't use static libraries of eigen. Commented this line all work well
Updated to new version of kobukilib

[issue #507] Solved Pose3D position fail.

---

CMakeLists.txt

solved bug in install python interfaces

[issue #592] solved bug in install python interfaces

---

CMakeLists.txt

now install all python files of jderobot interfaces well

[issue #592] now install all python files of jderobot interfaces well

---

src/tools/colorTuner_py/CMakeLists.txt

solved bug in colorTuner py instalation (issue #632 )

[issue #632] solved bug in colorTuner py instalation

---

src/tools/basic_component_py/gui/cameraWidget.py

solved bug in camera widget of basic_component_py
this PR solves #635

[issue #635] solved bug in camera widget of basic_component_py

---

src/tools/kobukiViewer/kobukiViewer.cfg

solved minimal bug in KobukiViewer.cfg (#637)

[issue #637] solved minimal bug in KobukiViewer.cfg

---

src/libs/roscompat/CMakeLists.txt
src/libs/roscompat/include/roscompat/listenerCamera.h
src/libs/roscompat/src/listenerCamera.cpp

Each interface will have a custom listener to connect ROS compatibility library.

[#552] Added specific listener for camera topics

---

Deps/vtk/CMakeLists.txt

Revert "[issue #663] deleted vtk of dependecy list."

---

src/drivers/ardrone_server/CMakeLists.txt
src/drivers/openni1Server/CMakeLists.txt
src/drivers/openniServer/CMakeLists.txt

#671 fixed cxx flags overwrite

---

src/drivers/gazeboserver/plugins/turtlebot/cfg/turtlebotplugin.cfg

Changed turtlebot Websocket port to 11010
this PR solves #634

[issue #634] Changed turtlebot Websocket port to 11010

---

cmake/pythonAux.cmake

[issue #691] Added pythonAux.cmake file

---

Deps/ros/CMakeLists.txt

changed ros jade dependency by ros kinetic
this PR solves #700

[issue #700] changed ros jade dependency by ros kinetic

---

src/tools/kobukiViewer/gui/widget/laserwidget.cpp

Changed lines for points in laserWidget of kovbukiViewer (#713)

[issue #713] Changed lines for points in laserWidget of kovbukiViewer

---

Deps/opencv/CMakeLists.txt
scripts/cmake/postinst

changed opencv package to ros-kinetic-opencv3 and post install pip to python2.
The others (pcl, vtk) not need be changed in code, only need be deleted from our apt repository
this PR solves #708

[issue #708] Changed Dependencies

---

src/drivers/ardrone_server/CMakeLists.txt
src/drivers/ardrone_server/include/ardrone_server/ardrone_driver.h

Added config.xml of ardrone_server to  installation (#689)

[issue #689] Added config.xml of ardrone_driver to package installation

---

scripts/docker/jderobot/oficial/Dockerfile
scripts/docker/jderobot/oficial/bin/rungzserver
scripts/docker/jderobot/oficial/installGzweb.sh
scripts/docker/jderobot/oficial/jderobot_entrypoint.sh

Updated oficial docker to 5.5.0
fix #734

[#734] Updated oficial docker to 5.5.0

---

CMakeLists.txt
src/drivers/gazeboserver/plugins/f1/CMakeLists.txt
src/drivers/gazeboserver/plugins/flyingKinect2/CMakeLists.txt
src/drivers/gazeboserver/plugins/roomba/CMakeLists.txt
src/drivers/gazeboserver/plugins/turtlebot/CMakeLists.txt
src/drivers/openni1Server/CMakeLists.txt
src/drivers/openniServer/CMakeLists.txt
src/libs/depthLib/DepthFilter.cpp
src/libs/depthLib/DepthSampler.cpp
src/tools/basic_component/CMakeLists.txt
src/tools/cameraview/CMakeLists.txt
src/tools/naoviewer/CMakeLists.txt
src/tools/navigatorCamera/CMakeLists.txt
src/tools/recorder2/CMakeLists.txt
src/tools/replayController/CMakeLists.txt
src/tools/replayer2/CMakeLists.txt
src/tools/rgbdViewer/CMakeLists.txt

Included Wall for the whole project.

#744 included all compilation warnings

---

src/libs/progeo/progeo.h

#763 progeo c api labeled as deprecated

---

scripts/docker/README.md

Improved the official JdeRobot Docker docs

Fixes #778 - Removed typos in Docker README.txt

---

src/drivers/gazeboserver/worlds/reconstruccion3D.world

Modified the world to use turtlebot robot instead of pioneer for the 3d reconstruction example.

[issue #786] Modified 3d_reconstruction world

---

src/tools/cameraviewjs/CMakeLists.txt
src/tools/cameraviewjs/cameraviewjs.in
src/tools/kobukiviewerjs/CMakeLists.txt
src/tools/kobukiviewerjs/kobukiviewerjs.in
src/tools/rgbdviewerjs/CMakeLists.txt
src/tools/rgbdviewerjs/rgbdviewerjs.in
src/tools/uavviewerjs/CMakeLists.txt
src/tools/uavviewerjs/uavviewerjs.in

Now to launch **cameraviewjs** only you need put:
<pre>
cameraviewjs
</pre>
for the other webtools is the same

[issue #800] created launcher for webtools

---

src/libs/jderobotcomm_cpp/CMakeLists.txt
src/libs/jderobotcomm_cpp/include/jderobot/comm/ice/cameraIceClient.hpp
src/libs/jderobotcomm_cpp/src/ice/cameraIceClient.cpp
src/tools/cameraview/CMakeLists.txt
src/tools/kobukiViewer/CMakeLists.txt

Solved bug in JdeRobotComm camera client (copied from parallelIce)

[issue #803] Solved bug in JdeRobotComm camera client (copied from parallelIce)

---

src/drivers/evicam_driver/CMakeLists.txt
src/drivers/evicam_driver/EVILib/EVI-D100.c++
src/drivers/evicam_driver/EVILib/EVI-D100.h
src/drivers/evicam_driver/EVILib/EVI-D100P.c++
src/drivers/evicam_driver/EVILib/EVI-D100P.h
src/drivers/evicam_driver/EVILib/EVI-D100g.c++
src/drivers/evicam_driver/EVILib/EVI-D100g.h
src/drivers/evicam_driver/EVILib/EVI-D30.c++
src/drivers/evicam_driver/EVILib/EVI-D30.h
src/drivers/evicam_driver/EVILib/EVI-D30g.c++
src/drivers/evicam_driver/EVILib/EVI-D30g.h
src/drivers/evicam_driver/EVILib/EVI-D31.c++
src/drivers/evicam_driver/EVILib/EVI-D31.h
src/drivers/evicam_driver/EVILib/EVI-D70.c++
src/drivers/evicam_driver/EVILib/EVI-D70.h
src/drivers/evicam_driver/EVILib/EVI-D70P.c++
src/drivers/evicam_driver/EVILib/EVI-D70P.h
src/drivers/evicam_driver/EVILib/EVI-D70g.c++
src/drivers/evicam_driver/EVILib/EVI-D70g.h
src/drivers/evicam_driver/EVILib/EVILib.c++
src/drivers/evicam_driver/EVILib/EVILib.h
src/drivers/evicam_driver/evicam_driver.cfg
src/drivers/evicam_driver/include/evicam_driver/interfaces/pantilti.hpp
src/drivers/evicam_driver/src/evicam_driver.cpp
src/drivers/evicam_driver/src/interfaces/pantilti.cpp
src/drivers/evicam_driver/src/test.cpp
src/drivers/evicam_driver/test.cfg
src/interfaces/slice/jderobot/pantilt.ice

maked driver to move EVI camera, only in position. For video use cameraserver

[issue #820] made driver to move EVI camera.

---

src/libs/easyiceconfig/CMakeLists.txt
src/libs/jderobotcomm_cpp/CMakeLists.txt

jderobotcomm and easyiceconfig now use ZeroCICE_LIBRARIES variable (#817)

[issue #817] jderobotcomm and easyiceconfig now use ZeroCICE_LIBRARIES variable

---

src/tools/visualHFSM/automatagui.py
src/tools/visualHFSM/generate.cpp
src/tools/visualHFSM/guinode.py

This pull request closes the issue #462.
Now, the interfaces created will be called by its name, not by its name + Prx as it was before

solving issue #462 and adapting prints to python3 format

---

CMakeLists.txt
scripts/metapackages/jderobot-deps-dev.info.in
scripts/metapackages/jderobot-deps.info.in

Setting ENABLE_ROS with OFF, you can disable ROS dependencies

[issue #782] added options to generate only ice packages

---

src/libs/easyiceconfig_py/easyiceconfig/hardcodedpaths.py.in

[issue #815] Solved bug in easyiceconfig_py

---

src/tools/visualHFSM/gui/configfile.glade

we unset application paint property of configfile glade diaolog to be able to have a default background. solves #846

[visualHFSM] solve bg problem of config dialog

---

src/tools/visualHFSM/CMakeLists.txt
src/tools/visualHFSM/automatagui.cpp
src/tools/visualHFSM/generate.cpp

Create c++ runtime gui as a shared library. solves isssue #841
New c++ template now links with the c++ runtime gui library.

Create c++ runtime gui as a shared library. solves #841

---

src/libs/jderobotcomm_cpp/src/cameraClient.cpp
src/libs/jderobotcomm_cpp/src/laserClient.cpp
src/libs/jderobotcomm_cpp/src/motorsClient.cpp
src/libs/jderobotcomm_cpp/src/pose3dClient.cpp

Solve throwing exception even if roscpp is found.

---

src/tools/visualStates/CMakeLists.txt
src/tools/visualStates/setup.sh

Solved getinterfaces.sh installation and updated setup.sh of visualStates to /opt/jderobot installation

[issue #890] Solved installation bug in visualStates

---

src/libs/comm_py/comm/cameraClient.py.only-ice.in
src/libs/comm_py/comm/cameraClient.py.ros.in
src/libs/comm_py/comm/ice/cameraIceClient.py
src/libs/comm_py/comm/ice/motorsIceClient.py
src/libs/comm_py/comm/laserClient.py.only-ice.in
src/libs/comm_py/comm/laserClient.py.ros.in
src/libs/comm_py/comm/motorsClient.py.only-ice.in
src/libs/comm_py/comm/motorsClient.py.ros.in
src/libs/comm_py/comm/pose3dClient.py.only-ice.in
src/libs/comm_py/comm/pose3dClient.py.ros.in
src/libs/comm_py/comm/ptMotorsClient.py.only-ice.in
src/libs/comm_py/comm/ptMotorsClient.py.ros.in
src/libs/comm_py/comm/rgbdClient.py.only-ice.in
src/libs/comm_py/comm/rgbdClient.py.ros.in

[issue #929] added default values to some config to comm_py

---

src/tools/colorTuner_py/filters/hsvFilter.py
src/tools/colorTuner_py/filters/rgbFilter.py
src/tools/colorTuner_py/filters/yuvFilter.py
src/tools/colorTuner_py/gui/controlWidget.py

[issue #883] solved bug in colorTuner

---

src/tools/visualStates_py/CMakeLists.txt
src/tools/visualStates_py/codegen/cpp/runtimegui.cpp
src/tools/visualStates_py/codegen/python/runtimegui.py
src/tools/visualStates_py/gui/cpprosgenerator.py
src/tools/visualStates_py/gui/filemanager.py

We create a standalone c++ ROS node. In the previous implementation runtime gui is used from jderobot installation, but with this pull request all python modules are transferred to ROS package.

Standalone c++ ROS node creation

---

scripts/docker/build_dockers.py
scripts/docker/docker_list.yaml
scripts/docker/jderobot/demos/cameraviewjs/Dockerfile
scripts/docker/jderobot/demos/cameraviewjs/democameraviewjs.sh
scripts/docker/jderobot/dev-only-ice/Dockerfile
scripts/docker/jderobot/official/Dockerfile
scripts/docker/jderobot/official/bin/kobukiviewerjs
scripts/docker/jderobot/official/bin/lsworlds
scripts/docker/jderobot/official/installGzweb.sh
src/drivers/cameraserver_py/CMakeLists.txt
src/tools/navigatorCamera/CMakeLists.txt

solved bug in cameraserver_py al deleted all references to /usr/local

[#976 & #977] solved bug in cameraserver_py al deleted all references to /usr/local

---

src/examples/visualStates/jderobot_comm/ice/obstacleAvoidanceCpp/obstacleAvoidanceCpp.xml
src/examples/visualStates/jderobot_comm/ice/obstacleAvoidancePython/obstacleAvoidancePython.xml
src/examples/visualStates/jderobot_comm/ros/obstacleAvoidanceCpp/obstacleAvoidanceCpp.xml
src/examples/visualStates/jderobot_comm/ros/obstacleAvoidancePython/obstacleAvoidancePython.xml
src/examples/visualStates/ros/obstacleAvoidanceCpp/obstacleAvoidanceCpp.xml
src/examples/visualStates/ros/obstacleAvoidancePython/obstacleAvoidancePython.xml

We provide examples of same behavior for 6 different interfaces.

[tools] [visualstates] examples are added to examples directory

---

src/tools/visualStates_py/codegen/cpp/state.cpp
src/tools/visualStates_py/codegen/python/state.py
src/tools/visualStates_py/gui/automatascene.py
src/tools/visualStates_py/gui/cppgenerator.py
src/tools/visualStates_py/gui/cpprosgenerator.py
src/tools/visualStates_py/gui/filemanager.py
src/tools/visualStates_py/gui/generator.py
src/tools/visualStates_py/gui/pythongenerator.py
src/tools/visualStates_py/gui/pythonrosgenerator.py
src/tools/visualStates_py/gui/state.py
src/tools/visualStates_py/gui/visualstates.py

functions and variables are defined as part of visualstates (fixes #995 )
also solves a bug; when you create a new automata previous automata's config, functions and variables are kept. We need to remove them.

[tools] [visualstates] functions and variables are defined as part of visualstates

---

src/examples/visualStates/jderobot_comm/ice/ArDrone/ArDrone.xml
src/examples/visualStates/jderobot_comm/ice/obstacleAvoidanceCpp/obstacleAvoidanceCpp.xml
src/examples/visualStates/jderobot_comm/ice/obstacleAvoidancePython/obstacleAvoidancePython.xml
src/examples/visualStates/jderobot_comm/ros/obstacleAvoidanceCpp/obstacleAvoidanceCpp.xml
src/examples/visualStates/jderobot_comm/ros/obstacleAvoidancePython/obstacleAvoidancePython.xml
src/examples/visualStates/ros/obstacleAvoidanceCpp/obstacleAvoidanceCpp.xml
src/examples/visualStates/ros/obstacleAvoidancePython/obstacleAvoidancePython.xml

Changing the previous visualstates examples for new functions and variables xml structure.
Also add a new ArDrone example behavior.
Those examples are compatible with version of visualstates after pull request #996

[tools] [visualstates] change the examples for new functions and variables xml structure.

---

src/drivers/gazeboserver/worlds/landing.world

This pull request fix the #1009 issue

Add landing.world to gazebo's worlds

---

src/interfaces/slice/jderobot/ptmotors.ice
src/libs/comm_py/comm/ice/ptMotorsIceClient.py

[#1004] Added timestamp to ptmotors

---

scripts/install_deps.sh

updated install script

---

src/libs/comm_py/comm/tools.py

Added checks for type checking while retrieving server type from the configuration file.
ref. #1099

Included type checks when retrieving server from config.

---

src/drivers/gazeboserver/models/hangar/model.config
src/drivers/gazeboserver/models/wall1/model.sdf
src/drivers/gazeboserver/models/wall2/model.sdf
src/drivers/gazeboserver/models/wall3/model.sdf
src/drivers/gazeboserver/models/wall4/model.sdf
src/drivers/gazeboserver/plugins/gymkhana/wall1.cc
src/drivers/gazeboserver/plugins/gymkhana/wall2.cc
src/drivers/gazeboserver/plugins/gymkhana/wall3.cc
src/drivers/gazeboserver/plugins/gymkhana/wall4.cc
src/drivers/gazeboserver/worlds/gymkhana.world

Following issue #1112 , the gymkhana world has been update.
The problem concerning collision with the hanger walls is yet to be tackled.

Gymkhana model updated.

---

src/drivers/gazeboserver/worlds/ArDroneBox.world

The world has been added to the gazebo's world repository. This fixes the #1145 issue.

Added ArDroneBox.world

---

src/drivers/PiBot/README.md

Partial improvement of PiBot description and shopping list

---

src/libs/comm_py/comm/ros/listenerCamera.py

The import sentence was missing for numpy.

Added missing np import. Fixed #1189.

---

src/interfaces/slice/jderobot/visualization.ice

New visualization.ice. Added a new function for the reception of segments, modified the old functions to be buffers of points and segments. Added the option to refresh the scene (in case you want)

issue #1167: Modify visualization.ice to visualize 3D segments

---

scripts/launch/roombaROS.launch

[Solves #1178] ROS launch file for roombaROS model

---

.gitignore
src/drivers/gazebo/plugins/pibot/motors.cc
src/drivers/gazebo/plugins/pibot/motors.h

when PiBot is 2 seconds without gettting velocities, It stops

[#1130] watchdog for pibot

---

assets/gazebo/worlds/vacuumRoom.world

Solves #1227 
Two modified worlds including robots with ROS interfaces for both vacuum_cleaner and vacuum_slam practices.

[Solve #1227] New ROS-based worlds for vacuum practices

---

assets/PiBot/README.md

Update of the component list for pibot

---

assets/gazebo/launch/example_drone.launch
assets/gazebo/worlds/example_drone.world

[##1285] example drone world

---

src/drivers/gazebo/plugins/pibot/CMakeLists.txt

[#1298] solved bug in cmakelists of gazebo pibot

---

src/drivers/PiBot/real/driver_documentation.md
src/drivers/PiBot/real/piBot.py

This is the latest versión of driver 'piBot.py', so, this pull request goes over issues #1309 #1308 #1297 #1282 #1281 and #1274

[driver]Last changes on driver piBot.py for real PiBot

---

src/drivers/PiBot/real/driver_documentation.md

There is written the driver piBot.py documentation except the last four methods (dameImagen, mostrarImagen, dameObjeto, dameSonarVisual)

[Driver real PiBot] Documentation

---

src/drivers/PiBot/real/driver_documentation.md

There is the complete documentation of driver piBot.py for real PiBot. This pull request is about issue 1294

[driver]Documentation for driver of real PiBot

---

src/drivers/PiBot/real/driver_documentation.md
src/drivers/PiBot/real/piBot.py

Detroyer method added for real PiBot driver

[Driver] Detroyer method added

---

src/drivers/PiBot/real/piBot.py

This is the improvement of methods "girarDerecha" and "girarIzquierda". Now, thay receive an angular speed by parameter. This pull request is about issue #1329

[driver]piBot.py for real PiBot

---

README.md

updated README with installation instructions

---

README.md

Addressing issue #1398 
Added some missing libraries for the source installation.
Corrected some typos.

Added missing libraries to README and corrected typos

---

src/libs/connector_py/.gitignore
src/libs/connector_py/CMakeLists.txt
src/libs/connector_py/connector/__init__.py
src/libs/connector_py/connector/connector.py
src/libs/connector_py/connector/ros/listenerLaser.py
src/libs/connector_py/connector/ros/listenerPose3d.py
src/libs/connector_py/connector/ros/publisherCmdVel.py
src/libs/connector_py/connector/ros/publisherMotors.py
src/libs/connector_py/connector/ros/threadPublisher.py

The connector library (currently in python), tries to replace the comm library which was used to work with both ROS and ICE. The new proposed package returns ROS Driver objects to the exercise.

Connector library for Python
